spring:
  application:
    name: spring-boot-persistence
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8081
  error:
    whitelabel:
      enabled: false
---
spring:
  profiles: dev
logging:
  level:
    .: DEBUG
    org.springframework: ERROR
    com.ctl: DEBUG
  file: ./log/persistence.log
  pattern:
    console: "%d %-6level [%t] %logger{25} - %msg %n"
    file: "%d %-6level [%t] %logger{25} - %msg %n"